
import sys
import os
import argparse
from datetime import datetime, timedelta, timezone

from dotenv import load_dotenv
from apify_client import ApifyClient

sys.path.append(
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..")
    )
)

from src.scraper.apify_macro import process_macro_events
from src.data.database import init_db, MacroEvent


def main():
    # Load environment variables
    load_dotenv()

    token = os.getenv("APIFY_API_TOKEN")

    # Command-line arguments
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--mock",
        action="store_true",
        help="Use mock data instead of Apify"
    )

    args = parser.parse_args()

    # Check API token
    if not token and not args.mock:
        print("Error: APIFY_API_TOKEN is missing in .env.")
        print("Please configure it or run with --mock.")
        sys.exit(1)

    # Initialize database
    print("Initializing database...")

    db_path = "sqlite:///data/macro_trading.db"

    Session = init_db(db_path)
    session = Session()

    # 180-day collection window
    end_date = datetime.now(timezone.utc)
    start_date = end_date - timedelta(days=180)

    print(
        f"Collection window: "
        f"{start_date.strftime('%Y-%m-%d')} to "
        f"{end_date.strftime('%Y-%m-%d')}"
    )

    raw_events = []

    # =========================================================
    # MOCK DATA
    # =========================================================
    if args.mock:

        print("Using mock data...")

        raw_events = [
            {
                "id": "mock_1",
                "eventName": "Core CPI (MoM)",
                "timestamp": "2023-10-12T12:30:00Z",
                "country": "United States",
                "currency": "USD",
                "category": "Inflation",
                "impact": "High",
                "actual": "0.3%",
                "forecast": "0.3%",
                "previous": "0.3%"
            },
            {
                "id": "mock_2",
                "eventName": "Nonfarm Payrolls",
                "timestamp": "2023-10-06T12:30:00Z",
                "country": "United States",
                "currency": "USD",
                "category": "Employment",
                "impact": "High",
                "actual": "336K",
                "forecast": "170K",
                "previous": "227K"
            },
            {
                "id": "mock_3",
                "title": "Invalid Date Event",
                "time": "InvalidDate",
                "actual": "100"
            }
        ]

    # =========================================================
    # REAL APIFY DATA
    # =========================================================
    else:

        print(
            "Calling Apify Actor: "
            "pintostudio/economic-calendar-data-investing-com"
        )

        client = ApifyClient(token)

        # Actor input
        run_input = {
            "timeFilter": "time_only",
            "country": "united states",
            "importances": "high",
            "fromDate": start_date.strftime("%Y-%m-%d"),
            "toDate": end_date.strftime("%Y-%m-%d")
        }

        try:

            # Start Actor
            run = client.actor(
                "pintostudio/economic-calendar-data-investing-com"
            ).call(
                run_input=run_input,
                max_items=1000
            )

            if not run:
                raise RuntimeError(
                    "Apify Actor did not return a run."
                )

            # Get run ID
            if isinstance(run, dict):
                run_id = run.get("id")
            else:
                run_id = getattr(run, "id", None)

            if not run_id:
                raise RuntimeError(
                    "Could not find Apify run ID."
                )

            print(
                f"Apify run completed: {run_id}"
            )

            # Get run client
            run_client = client.run(run_id)

            # Get run information
            run_info = run_client.get()

            print(
                f"Apify run status: "
                f"{run_info.get('status')}"
            )

            # Check status
            if run_info.get("status") != "SUCCEEDED":
                raise RuntimeError(
                    f"Apify run did not succeed. "
                    f"Status: {run_info.get('status')}"
                )

            # Read dataset generated by this run
            raw_events = list(
                run_client.iterate_dataset_items()
            )

            print(
                f"Retrieved {len(raw_events)} items from Apify."
            )

        except Exception as e:

            print(
                f"Error calling Apify: {e}"
            )

            sys.exit(1)

    # =========================================================
    # CHECK RAW DATA
    # =========================================================

    if not raw_events:

        print("No events returned.")

        return

    print(
        f"Received {len(raw_events)} raw events."
    )

    # =========================================================
    # PROCESS EVENTS
    # =========================================================

    df_events = process_macro_events(
        raw_events
    )

    if df_events.empty:

        print(
            "No valid events parsed."
        )

        return

    print(
        f"Processed {len(df_events)} valid events."
    )

    # =========================================================
    # SAVE TO DATABASE
    # =========================================================

    print(
        "Saving to database (merging duplicates)..."
    )

    existing_ids = set(
        row[0]
        for row in session.query(
            MacroEvent.event_id
        ).all()
    )

    new_events = df_events[
        ~df_events["event_id"].isin(
            existing_ids
        )
    ].copy()

    # Insert new events
    if not new_events.empty:

        # Convert timezone-aware UTC timestamps
        # to naive UTC for SQLite.

        if "event_time_utc" in new_events.columns:

            new_events["event_time_utc"] = (
                new_events["event_time_utc"]
                .dt.tz_convert(None)
            )

        if "scraped_at" in new_events.columns:

            new_events["scraped_at"] = (
                new_events["scraped_at"]
                .dt.tz_convert(None)
            )

        new_events.to_sql(
            "macro_events",
            session.get_bind(),
            if_exists="append",
            index=False
        )

        print(
            f"Inserted {len(new_events)} new events "
            f"to macro_events table."
        )

    else:

        print(
            "No new events to insert "
            "(all duplicates)."
        )

    # =========================================================
    # SUMMARY
    # =========================================================

    print("\n--- Ingestion Summary ---")

    print(
        f"Total valid events processed: "
        f"{len(df_events)}"
    )

    print(
        f"Events with Actual values: "
        f"{df_events['actual_value'].notna().sum()}"
    )

    print(
        f"Events with Forecast values: "
        f"{df_events['forecast_value'].notna().sum()}"
    )

    print(
        f"Events with calculated Surprise: "
        f"{df_events['macro_surprise'].notna().sum()}"
    )


if __name__ == "__main__":
    main()
